language: php
php:
  - "5.4"
  - "5.3"
install:
  - composer install
  - npm install -g jshint@2.5.6
  - npm install -g jscs@1.6.2
script:
  - ./vendor/bin/parallel-lint --exclude vendor .
  - ./vendor/bin/phpcs . --standard=./test/codesniffer --ignore=vendor/* --extensions=php --report=full -s --tab-width=4
  - jshint .
  - jscs .
notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-qa"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit}: %{author}) %{message} - %{build_url}"
